### PR TITLE
Add a parameterize method

### PR DESCRIPTION
**Pull request by brunto**
Fixes: #8 

Added the same method as the one in the Rails framework: https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflector/transliterate.rb#L121

### CODE REVIEW

**Review by jwoertink — CHANGES_REQUESTED** [review]
Sorry for the late review! Apparently I wasn't watching this repo lol. 

I'm sure the implementation is fine, but can you add some specs for it? You can use the rails examples in their docs as test cases https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflector/transliterate.rb#L98-L115

**Comment by jwoertink** [comment]
Hey @brunto checking back in here. Let me know if you're able to add some specs for this. I'd love to get it in on the next release. Thanks!

**Comment by brunto** [comment]
Hi @jwoertink, yes, I'll do it quickly.

**Comment by brunto** [comment]
Tests added. Next step looking for the transliterate method.

**Review by jwoertink — APPROVED** [review]
Awesome! Thanks for adding this in.

**Comment by jwoertink** [comment]
> Tests added. Next step looking for the transliterate method.

We actually use a `transliterate` method from the Cadmium shard https://github.com/cadmiumcr/transliterator. It might be a lot for us to pull that in and manage it, so I'd say this parameterize method is plenty. Thanks!

**Comment by brunto** [comment]
Just realize that `Cadmium::Transliterator` has the method `Cadmium::Transliterator.parameterize`

**Pull request merged**
